version: "3.9"
services:

  mariadb:
    image: mariadb:10.5.8-focal
    environment:
      - MYSQL_DATABASE=${MARIADB_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./config/mariadb:/docker-entrypoint-initdb.d/
  

  ravendb:
    image: ravendb/ravendb
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Setup_Mode=None
    ports:
      - 8888:8080
    volumes:
      - ./ravendb_data:/opt/RavenDB/Server/RavenData


  message-queue:
    image: rabbitmq:3-management-alpine
    environment: 
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
        
  
  posts-db-provider:
    image: druzio-posts-db-provider
    environment:          
      - RAVENDB_URL=${RAVENDB_URL}
      - RAVENDB_DATABASE=${PS_DB_NAME}      
      - PORT=80

    deploy:
      restart_policy:
        condition: any

    ports:
      - "80"
    depends_on:
      - ravendb


  email-service:
    image: druzio-email-service
    environment:          
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - AMQP_USERNAME=${AMQP_USERNAME}
      - AMQP_PASSWORD=${AMQP_PASSWORD}

    deploy:
      restart_policy:
        condition: any

    ports:
      - "80"
    depends_on:
      - message-queue


  image-service:
    image: druzio-image-service
    environment:          
      - HOST=${IS_HOST}
      - PORT=80

    deploy:
      restart_policy:
        condition: any

    ports:
      - "80"


  posts-service:
    image: druzio-posts-service
    environment:          
      - HOST=${PS_HOST}
      - PORT=80

      - DB_PROVIDER_URL=${PS_DB_PROVIDER_URL}
      - USER_SERVICE_URL=${US_URL}
      - USER_RELATION_SERVICE_URL=${URS_URL}

    deploy:
      restart_policy:
        condition: any

    ports:
      - "80"

    depends_on:
      - posts-db-provider
      # - user-service
      # - user-relations-service
       

  # user-service:
  #   image: druzio-user-service
  #   environment:          
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_ADDRESS=${DB_ADDRESS}
  #     - DB_NAME=${US_DB_NAME}
      
  #     - AMQP_HOST=${AMQP_HOST}
  #     - AMQP_PORT=${AMQP_PORT}
  #     - AMQP_USERNAME=${AMQP_USERNAME}
  #     - AMQP_PASSWORD=${AMQP_PASSWORD}
      
  #     - JWT_SECRET=${JWT_SECRET}

  #     - PORT=":80"
      
  #   deploy:
  #     restart_policy:
  #         condition: any

  #   ports:
  #     - "80"
  #   depends_on:
  #     - mariadb
  #     - message-queue

  # user-relations-service:
  #   image: druzio-user-relations-service
  #   environment:          
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_ADDRESS=${DB_ADDRESS}
  #     - DB_NAME=${URS_DB_NAME}
      
  #     - AMQP_HOST=${AMQP_HOST}
  #     - AMQP_PORT=${AMQP_PORT}
  #     - AMQP_USERNAME=${AMQP_USERNAME}
  #     - AMQP_PASSWORD=${AMQP_PASSWORD}
      
  #     - JWT_SECRET=${JWT_SECRET}

  #     - PORT=":80"
      
  #   deploy:
  #     restart_policy:
  #       condition: any

  #   ports:
  #     - "80"
  #   depends_on:
  #     - mariadb
  #     - message-queue

  # chat-service:
  #   image: druzio-chat-service
  #   environment:          
  #     - DB_URL=${RAVENDB_URL}
  #     - DB_NAME=${CS_DB_NAME}    

  #     - AMQP_HOST=${AMQP_HOST}
  #     - AMQP_PORT=${AMQP_PORT}
  #     - AMQP_USERNAME=${AMQP_USERNAME}
  #     - AMQP_PASSWORD=${AMQP_PASSWORD}
      
  #     - JWT_SECRET=${JWT_SECRET}

  #     - HTTP_PORT=":80"
  #     - WS_PORT="8010"
      
  #   deploy:
  #     restart_policy:
  #       condition: any

  #   ports:
  #     - "80"
  #   depends_on:
  #     - ravendb
  #     - message-queue

  frontend-service:
    image: druzio-frontend-service

  http-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
    depends_on:
      - frontend-service
      # - user-service
      # - user-relations-service
      # - chat-service
      - posts-db-provider
      - posts-service
      - image-service
    ports:
      - 3000:80

networks:
  default:
    driver: bridge
